# Blue 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdconverter-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      labels:
        app: web
        version: blue
    spec:
      containers:
        - name: web
          image: localhost/mdconverter:v1
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
---
# Green
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdconverter-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      version: green
  template:
    metadata:
      labels:
        app: web
        version: green
    spec:
      containers:
        - name: web
          image: localhost/mdconverter:v2
          ports:
            - containerPort: 8000
          env:
            - name: ENABLE_OCR
              value: "1"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
---
# Switch de trafico
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
    version: blue
  ports:
    - port: 80
      targetPort: 8000
